bump critical to v4
updating to v5 causes:
```
[11ty] 1. Error in your Eleventy config file '.eleventy.js'. (via EleventyConfigError)
[11ty] 2. require() cannot be used on an ESM graph with top-level await. Use import() instead. To see where the top-level await comes from, use --experimental-print-required-tla.
[11ty]
[11ty] Original error stack trace: Error [ERR_REQUIRE_ASYNC_MODULE]: require() cannot be used on an ESM graph with top-level await. Use import() instead. To see where the top-level await comes from, use --experimental-print-required-tla.
[11ty]     at ModuleJobSync.runSync (node:internal/modules/esm/module_job:392:13)
[11ty]     at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:360:47)
[11ty]     at loadESMFromCJS (node:internal/modules/cjs/loader:1385:24)
[11ty]     at Module._compile (node:internal/modules/cjs/loader:1536:5)
[11ty]     at Object..js (node:internal/modules/cjs/loader:1706:10)
[11ty]     at Module.load (node:internal/modules/cjs/loader:1289:32)
[11ty]     at Function._load (node:internal/modules/cjs/loader:1108:12)
[11ty]     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
[11ty]     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
[11ty]     at Module.require (node:internal/modules/cjs/loader:1311:12)
ERROR: "eleventy:prod" exited with 1.
```